Repository game-devs-csf/RL-environments, pull requests merged in 2023-11, with the labels that each got.

#7 feature/import and export models
  baseMdl/__init__.py
  baseMdl/mdl.py
  examples/cartpole_import_export_models.py
  examples/cartpole_tests.py
  examples/model_1.npy
  examples/model_2.npy
  examples/model_3.npy
  examples/model_4.npy
Labels: enhancement, environment

#10 Imports the CTF and football games
  game/__init__.py
  game/captureTheFlag.py
  game/football.py
Labels: environment

#11 Feature/pre commit hooks
  .github/workflows/ruff.yml
  .pre-commit-config.yaml
  README.md
  baseEnv/env.py
  baseMdl/mdl.py
  cartPole/cartpole.py
  dev-environment.yml
  examples/cartpole_import_export_models.py
  examples/cartpole_tests.py
  examples/rotation_test.py
  game/captureTheFlag.py
  game/football.py
Labels: enhancement
